"""add label

Revision ID: 03b5a07718f9
Revises: ff6357189a84
Create Date: 2026-05-06 10:30:04.565691

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '03b5a07718f9'
down_revision = 'ff6357189a84'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labels',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('namespace', sa.VARCHAR(length=32), server_default=sa.text("'default'"), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('root_id', sa.BigInteger(), nullable=False),
    sa.Column('path', sa.VARCHAR(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_labels_ns_enabled', 'labels', ['namespace', 'enabled'], unique=False)
    op.create_index('ix_labels_ns_level', 'labels', ['namespace', 'level'], unique=False)
    op.create_index('ix_labels_ns_name', 'labels', ['namespace', 'name'], unique=False)
    op.create_index('ix_labels_ns_parent_sort', 'labels', ['namespace', 'parent_id', 'sort_order'], unique=False)
    op.create_index('ix_labels_ns_root', 'labels', ['namespace', 'root_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_labels_ns_root', table_name='labels')
    op.drop_index('ix_labels_ns_parent_sort', table_name='labels')
    op.drop_index('ix_labels_ns_name', table_name='labels')
    op.drop_index('ix_labels_ns_level', table_name='labels')
    op.drop_index('ix_labels_ns_enabled', table_name='labels')
    op.drop_table('labels')
    # ### end Alembic commands ###
