"""init_project

Revision ID: 21f977a1e758
Revises: 
Create Date: 2026-05-02 12:11:18.038004

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision = '21f977a1e758'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_permissions',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('group_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('api_path', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'ENABLED'"), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu_permissions',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('component', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'ENABLED'"), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_data_scope_rules',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('view_scope', sa.Enum('SELF', 'ALL', 'DEPT', 'DEPT_AND_SUB', 'CUSTOM', name='datascope', native_enum=False), server_default=sa.text("'SELF'"), nullable=False),
    sa.Column('edit_scope', sa.Enum('SELF', 'ALL', 'DEPT', 'DEPT_AND_SUB', 'CUSTOM', name='datascope', native_enum=False), server_default=sa.text("'SELF'"), nullable=False),
    sa.Column('custom_rule_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_role_resource_active', 'role_data_scope_rules', ['role_id', 'resource_type', 'is_active'], unique=False)
    op.create_index('ux_role_resource', 'role_data_scope_rules', ['role_id', 'resource_type'], unique=True)
    op.create_table('role_grant_jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('api_permission_ids', sa.JSON(), nullable=False),
    sa.Column('data_scope_rules', sa.JSON(), nullable=False),
    sa.Column('operator_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('APPLYING', 'SYNCED', 'SYNC_FAILED', name='rolegrantjobstatus', native_enum=False), server_default=sa.text("'APPLYING'"), nullable=False),
    sa.Column('synced', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_role_grant_role_status', 'role_grant_jobs', ['role_id', 'status'], unique=False)
    op.create_index('ux_role_grant_request_id', 'role_grant_jobs', ['request_id'], unique=True)
    op.create_table('role_menu_permissions',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('menu_permission_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_role_menu_permissions_menu_permission_id', 'role_menu_permissions', ['menu_permission_id'], unique=False)
    op.create_index('ix_role_menu_permissions_role_id', 'role_menu_permissions', ['role_id'], unique=False)
    op.create_index('ux_role_menu_permissions', 'role_menu_permissions', ['role_id', 'menu_permission_id'], unique=True)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_index('ix_role_permissions_permission_id', 'role_permissions', ['permission_id'], unique=False)
    op.create_index('ix_role_permissions_role_id', 'role_permissions', ['role_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_system', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('parent_role_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    op.create_table('user_data_scope_rules',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('view_scope', sa.Enum('SELF', 'ALL', 'DEPT', 'DEPT_AND_SUB', 'CUSTOM', name='datascope', native_enum=False), server_default=sa.text("'SELF'"), nullable=False),
    sa.Column('edit_scope', sa.Enum('SELF', 'ALL', 'DEPT', 'DEPT_AND_SUB', 'CUSTOM', name='datascope', native_enum=False), server_default=sa.text("'SELF'"), nullable=False),
    sa.Column('custom_rule_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_resource_active', 'user_data_scope_rules', ['user_id', 'resource_type', 'is_active'], unique=False)
    op.create_index('ux_user_resource', 'user_data_scope_rules', ['user_id', 'resource_type'], unique=True)
    op.create_table('user_roles',
    sa.Column('user_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_index('ix_user_roles_role_id', 'user_roles', ['role_id'], unique=False)
    op.create_index('ix_user_roles_user_id', 'user_roles', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('token_version', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_user_roles_user_id', table_name='user_roles')
    op.drop_index('ix_user_roles_role_id', table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index('ux_user_resource', table_name='user_data_scope_rules')
    op.drop_index('ix_user_resource_active', table_name='user_data_scope_rules')
    op.drop_table('user_data_scope_rules')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_table('roles')
    op.drop_index('ix_role_permissions_role_id', table_name='role_permissions')
    op.drop_index('ix_role_permissions_permission_id', table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index('ux_role_menu_permissions', table_name='role_menu_permissions')
    op.drop_index('ix_role_menu_permissions_role_id', table_name='role_menu_permissions')
    op.drop_index('ix_role_menu_permissions_menu_permission_id', table_name='role_menu_permissions')
    op.drop_table('role_menu_permissions')
    op.drop_index('ux_role_grant_request_id', table_name='role_grant_jobs')
    op.drop_index('ix_role_grant_role_status', table_name='role_grant_jobs')
    op.drop_table('role_grant_jobs')
    op.drop_index('ux_role_resource', table_name='role_data_scope_rules')
    op.drop_index('ix_role_resource_active', table_name='role_data_scope_rules')
    op.drop_table('role_data_scope_rules')
    op.drop_table('menu_permissions')
    op.drop_table('api_permissions')
    # ### end Alembic commands ###
